[project]
name = "anki-browse-web"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["anki"]

[dependency-groups]
dev = ["ruff"]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["I"] # isort for import sorting

[tool.ruff.format]
quote-style = "double"
